### ISSUE TITLE
Advanced Search Time Filter toggle opens multiple filters

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#22]
When toggling the Time Filter in the Advanced Search, this opens several Time Filter boxes.

![screen shot 2017-10-04 at 12 00 08](https://user-images.githubusercontent.com/19243127/31172870-2d02184c-a8fd-11e7-9861-6a4ab0630f59.png)

Occasionally, multiple time sliders appear:

![screen shot 2017-10-04 at 12 11 57](https://user-images.githubusercontent.com/19243127/31172890-3f9a5b9a-a8fd-11e7-9a78-5a0a96361141.png)

**Comment by markdoub** [comment]
I just pushed a change that fixes the problem (at least for my docker branch).
The first time-filter widget in the advanced search has index=0.
`if ( typeof self.index !== 'undefined')`
was not handling this case. I changed it to:
`if ( typeof self.index !== 'undefined')`

**Comment by azerbini** [comment]
@markdoub  correct, your fix works. Closing this.
