### ISSUE TITLE
Advanced Search - Search doesn't update on inverted queries of additional search boxes

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#24]
When inverting a search tag in the second or subsequent search boxes, the results do not get updated:

![screen shot 2017-10-05 at 16 17 29](https://user-images.githubusercontent.com/19243127/31235305-168a7536-a9e9-11e7-9803-411cee8f1332.png)
![screen shot 2017-10-05 at 16 17 43](https://user-images.githubusercontent.com/19243127/31235310-1978c9fa-a9e9-11e7-9581-26c90e8544f6.png)

**Comment by markdoub** [comment]
Should be fixed now by commit: eeef6f4
I think time filters where not working either when used in 2nd, 3d etc searchbox (they where working in some cases, e.g. when an inverted filter was applied in the first searchbox!)

**Comment by azerbini** [comment]
Meets requirements
