### ISSUE TITLE
User Analytics - 'View on site' link not working

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#31]
![screen shot 2017-10-10 at 13 30 49](https://user-images.githubusercontent.com/19243127/31386623-572166de-adbf-11e7-8405-b74a0906bf96.png)

Clicking on 'View on Site' returns 404.

**Comment by markdoub** [comment]
I can see the link is already there when the docker branch starts and it's broken there to. Is it there in the production server? What page should it link?

**Comment by azerbini** [comment]
@markdoub  No, it's not there. Not sure where it comes from?

**Comment by ahaith** [comment]
Latest version of ox-it/user-analytics-master removes this link.

**Comment by azerbini** [comment]
@ahaith are you packaging a different PR? Or should I just fork that branch on your repo?

**Comment by ahaith** [comment]
It's actually just removing a few lines from eamena/eamena/templates/admin/auth/user/change_form.html

It might be easiest to just repeat locally rather than trying to do it through git.

**Comment by azerbini** [comment]
@ahaith Great will do
