### ISSUE TITLE
Shape file export problem

### ISSUE THREAD

**Issue by MattHobson** [azerbini/eamena_v3#45]
A .shp export using more than one country input exports no shapefile. This is true at least for Libya (Modern Country Territory), Tunisia (Modern Country Territory). Only the .csv with the resource relations exports.

**Comment by azerbini** [comment]
@MattHobson Not sure I am able to replicate your problem. My search below, returns 5000+ results which, for the sake of time, I then filtered by geometry to restrict to 765. I extracted as SHP and got exactly 765 records spread across Tunisia and Libya (679 points, 2 lines, and the remainder polygons). 

![screen shot 2017-10-13 at 17 29 09](https://user-images.githubusercontent.com/19243127/31556244-0da5dc40-b03c-11e7-9dab-e3b70e93c509.png)

**Comment by MattHobson** [comment]
Hi Andrea,

It looks like you did a search using a polygon rather than typing 'Libya' and 'Tunisia' into the search bar. You have found a 'work-around' solution, but I still do not understand why the problem with trying to achieve this with search terms causes a problem.

M

Sent from my iPhone

On 13 Oct 2017, at 17:30, Andrea Zerbini <notifications@github.com<mailto:notifications@github.com>> wrote:


@MattHobson<https://github.com/matthobson> Not sure I am able to replicate your problem. My search below, returns 5000+ results which, for the sake of time, I then filtered by geometry to restrict to 765. I extracted as SHP and got exactly 765 records spread across Tunisia and Libya (679 points, 2 lines, and the remainder polygons).

[screen shot 2017-10-13 at 17 29 09]<https://user-images.githubusercontent.com/19243127/31556244-0da5dc40-b03c-11e7-9dab-e3b70e93c509.png>

**Comment by azerbini** [comment]
@MattHobson No Matt, I didn't. I only used the polygon restriction, as i said above, in order to restrict the massive dataset that Libya + Tunisia would have returned (ie over 5000 records). If you look at the screenshot, you will see I have used the term search as you indicated you had in your original ticket.

**Comment by MattHobson** [comment]
Hmm, not sure what is happening there then. I recreated the problem several times. I'll have a look again tomorrow.

M

Sent from my iPhone

On 13 Oct 2017, at 20:06, Andrea Zerbini <notifications@github.com<mailto:notifications@github.com>> wrote:


@MattHobson<https://github.com/matthobson> No Matt, I didn't. I  g there the only used the polygon restriction, as i said above, in order to restrict the massive dataset that Libya + Tunisia would have returned (ie over 5000 records). If you look at the screenshot, you will see I have used the term search as you indicated you had in your original ticket.

**Comment by MattHobson** [comment]
The problem may be to do with the number of records returned in that case? I cannot recreate the problem today, but only because now when I enter Libya and Tunisia together I get no results returned.

**Comment by azerbini** [comment]
@MattHobson Hi Matt, are you sure you are entering the correct search ? This is what I get when I search for records in Tunisia OR Libya:
![screen shot 2017-10-17 at 14 44 19](https://user-images.githubusercontent.com/19243127/31668327-d4d732f4-b349-11e7-9a8c-83d53a1c2688.png)

**Comment by MattHobson** [comment]
Are you using the advanced search bar for that? I only see the AND\OR functions on the advanced search bar, and the problem I am describing is with the current database search bar. Sorry, I only realise now that my comments are probably very confusing for that reason.

**Comment by azerbini** [comment]
I am not using the Advanced Search @MattHobson. I am using the standard search, but selecting 'Or' as the operator ruling the relation between the two terms. I will cover all the nuances of the new search in the docs.

**Comment by azerbini** [comment]
Closing this as no further evidence has been provided of this being a bug.
