### ISSUE TITLE
Database field names are too long

### ISSUE THREAD

**Issue by MattHobson** [azerbini/eamena_v3#46]
Shapefile column titles are limited to 10 characters – but all Eamena field names are not currently identifiable by their first 10 characters. E.g. After saving an export as a shapefile it becomes impossible to tell which field is SITE_FUNCTION_TYPE and which is SITE_FUNCTION_CERTAINTY_TYPE, other than by looking at the data itself.

**Comment by MattHobson** [comment]
Additionally, if we did ever write SQL queries, every TABLE name and FIELD name should probably be written in lower case. This is because postgreSQL assumes everything is lowercase. If you had a table called 'Locations' and you queried 'SELECT * FROM Locations' it would give you an error telling you that no such table exists. If there are any capitals, one then needs to use quotations around every TABLE and FIELD name if you want postgreSQL know that it should be case sensititve. E.g. query SELECT * FROM "Location". I had this problem when I migrated the Tunisian Sites and Monuments Access database into postgres, and it took me a while to figure out what the problem was. It was so difficult to write queries I had to just change everything to lower case to remain sane. Something to think about if we ever get remote access working.

**Comment by azerbini** [comment]
@MattHobson If we ever were to do SQL queries, we would perform them on our current Postgres schema, where tables and fields are, indeed, all lower case. What you call 'Field Names' are actually Node names, and correspond to the CIDOC CRM node names in our ontology. They are stored in a series of tables within the ontology schema of the Postgres db (see Arches backend schema).

What you are **really** asking here though, is that we change the way that CIDOC nodes are mapped when exported to CSV and SHP. We can continue this discussion in the related ticket #47, which is more to the point.

**Comment by MattHobson** [comment]
Ok

Sent from my iPhone

On 13 Oct 2017, at 17:36, Andrea Zerbini <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #46<https://github.com/azerbini/eamena_v3/issues/46>.
