### ISSUE TITLE
Improve JSON mapping schema for CSV and SHP export

### ISSUE THREAD

**Issue by MattHobson** [azerbini/eamena_v3#47]
In current standard .csv export format, the concatenation of things like site_function_type  into one field makes it extremely difficult to categorize based on these fields.

**Comment by azerbini** [comment]
@MattHobson Suggestions on a simplified CSV mapping schema are most welcome. Please feel free to email them to me. However, I should emphasise that any new schema should maintain the full range of EAMENA nodes.

**Comment by MattHobson** [comment]
I expect we will need to talk in person about this once I get back from Tunisia in December. If I could get the remote access working that we have been discussing, I could see more clearly how the current database is structured (rather than relying on the documentation provided with Arches v3) and perhaps make some suggestions. I have found DBVisualizer or something somilar useful in this regard with other databases. M

**Comment by MattHobson** [comment]
*similar

**Comment by MattHobson** [comment]
I quick fix would be to allow more than one row per site (E27) and not to concatenate any of the cells. This would be immediately useful for the training in November 2017.

**Comment by MattHobson** [comment]
I believe Andrea you also wanted me to add the issue here about the length of the Node labels. When exporting data, which is then saved a shapefile the Node names are limited to 10 characters. This causes a problem in that, after saving an export as a shapefile, it becomes impossible to tell which Shapefile field is SITE_FUNCTION_TYPE and which is SITE_FUNCTION_CERTAINTY_TYPE, other than by looking at the data itself.

**Comment by azerbini** [comment]
@MattHobson  Not sure what your last comment means. At present, when exporting to Shapefile only three fields are mapped: primary name, arches id, and type. Where have you encountered this issue ?

**Comment by MattHobson** [comment]
I mean after you join the attributes contained in a CSV export to the geometry of the Shapefile export, and then save the joined files as a Shapefile.

**Comment by azerbini** [comment]
@MattHobson What you are describing is not a limitation of our database, but rather a limitation of shapefiles, which use DBF to store non geometric data. DBF has a header length limit of 10 characters (see, e.g.  https://gis.stackexchange.com/questions/15784/how-to-bypass-10-character-limit-of-field-name-in-shapefiles). The problem can be addressed with an improved field mapping. I have  quickly drawn up a more succinct mapping schema to shp, have a try at exporting to SHP now on the testing db (no need to go through the convoluted system of joining to CSV export).

**Comment by MattHobson** [comment]
Great! Thank you Andrea. That looks much better. What do you think about altering the mapping schema to shape to allow multiple entries per E27 and not concatenating any cells in the results table?

**Comment by MattHobson** [comment]
I imagine this would work quite well for basic mapping queries in QGIS

**Comment by MattHobson** [comment]
As it is, it is already vastly improved.

I am querying reasonably successfully using the QGIS query builder like so:

"Interpretat" LIKE '%Settlement%'  AND "Period" LIKE '%Roman%' AND "Condition"  LIKE 'Poor' OR "Condition"  LIKE  'Very Bad'

This returns all of the Roman period settlement sites deemed to be in poor or very bad condition.

I think we can demonstrate that as a tutorial. If we show them that and the advanced search functions then they can use a combination of the two methods for analysing the data.

I do think we need to change the How-to guide to advise that every site gets given point geometry and that polygons should not replace the point but be additional to it. That way it is easy to create maps with the entire dataset using one shapefile export rather than having to run the same query across shapefiles for lines, points and polygons.

**Comment by azerbini** [comment]
@MattHobson  your suggestion to unpack our nested heritage data on multiple lines of a bidimensional file such as a csv does not strike me as the correct way to proceed here. There are several reasons for this, and this thread isn't about this topic anyhow. 

Glad the new mapping has made a difference for you.  I am going to make some more improvements to it, then I will commit the new mapping file to the repo and close this discussion.

**Comment by MattHobson** [comment]
Ok well as I say I am managing to do some querying now, so things are not so urgent. I will give you a phonecall sometime about the 'unpacking' issue. To my mind, if we have several different export options that allow users to perform different sorts of queries, it could not be a bad idea to allow that. Thanks again for the improvements. M

**Comment by azerbini** [comment]
9df21b2f97484c273c76f9259fce50aacfd9451e meets requirements
