### ISSUE TITLE
Related Resources search - JSON export breaks

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#55]
JSON export of Related Resources returns a void ES object and breaks.
<img width="799" alt="screen shot 2017-10-25 at 15 13 40" src="https://user-images.githubusercontent.com/19243127/32003487-1eef3776-b997-11e7-8429-ab5cf4c1b56d.png">

**Comment by ahaith** [comment]
I think this should be fixed by PR #56.

**Comment by azerbini** [comment]
Meets requirements
