### ISSUE TITLE
Export to SHP throws Exception  The shape's type (3) must match the type of the shapefile (8).

### ISSUE THREAD

**Issue by eamena-github** [azerbini/eamena_v3#81]
After upgrading pyshp to 2.0.0 dev, this exception has now developed.

![error1](https://user-images.githubusercontent.com/32707884/34041813-aaa20d94-e191-11e7-968c-751cad3f6324.PNG)
![error2](https://user-images.githubusercontent.com/32707884/34041816-ad0f447a-e191-11e7-972b-fe2fd8e5091c.PNG)

**Comment by azerbini** [comment]
Meets requirements
