### ISSUE TITLE
Adding maps under info resources - is listed in bibliography instead of maps

### ISSUE THREAD

**Issue by eamena-github** [azerbini/eamena_v3#85]
Add map as information resource, link to heritage report, and in heritage report - related resources - it will be listed under bibliogra[hy, not maps (see i.e. st cath's monastery)

**Comment by eamena-github** [comment]
Also, related to this, they show up in related resources list under their INFORMATION-NUMBER, rather than (as other related refs) under a title. Would be easier to recognise what's what from a title - can this be changed?

**Comment by azerbini** [comment]
The reason is that you have not filled in a Sheet Number, but only a Sheet name. I have now changed the script to recognise a Map title whether it comes from Sheet number or from Sheet name.
